### ISSUE TITLE
Not picking up exceptions from aws-sdk-core?

### ISSUE THREAD

**Issue by silasb** [h3poteto/rollbar-shoryuken#7]
For code that occurs within the worker this gem is working nicely. 😄 

For code that exists outside of the user-defined code it doesn't seem to pickup the exception.  Looking at you `aws-sdk-core`.

Here is an example reduced traceback:

```
2020-05-28T13:46:52Z 9 TID-2zqc ERROR: Processor failed: Access to the resource https://sqs.us-east-1.amazonaws.com/111111222233/some-queue.fifo is denied.
2020-05-28T13:46:52Z 9 TID-2zqc ERROR: /usr/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.94.0/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
/usr/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.94.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
/usr/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.94.0/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
/usr/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.94.0/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
/usr/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.94.0/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
/usr/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.94.0/lib/seahorse/client/plugins/response_target.rb:23:in `call'
/usr/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.94.0/lib/seahorse/client/request.rb:70:in `send_request'
/usr/lib/ruby/gems/2.7.0/gems/aws-sdk-sqs-1.24.0/lib/aws-sdk-sqs/client.rb:961:in `delete_message_batch'
/usr/lib/ruby/gems/2.7.0/gems/shoryuken-5.0.4/lib/shoryuken/queue.rb:24:in `delete_messages'
/usr/lib/ruby/gems/2.7.0/gems/shoryuken-5.0.4/lib/shoryuken/middleware/server/auto_delete.rb:12:in `call'
/usr/lib/ruby/gems/2.7.0/gems/shoryuken-5.0.4/lib/shoryuken/middleware/chain.rb:100:in `block in invoke'
/usr/lib/ruby/gems/2.7.0/gems/shoryuken-5.0.4/lib/shoryuken/middleware/server/exponential_backoff_retry.rb:8:in `call'
/usr/lib/ruby/gems/2.7.0/gems/shoryuken-5.0.4/lib/shoryuken/middleware/chain.rb:100:in `block in invoke'
/usr/lib/ruby/gems/2.7.0/gems/shoryuken-5.0.4/lib/shoryuken/middleware/server/timing.rb:12:in `call'
/usr/lib/ruby/gems/2.7.0/gems/shoryuken-5.0.4/lib/shoryuken/middleware/chain.rb:100:in `block in invoke'
/usr/lib/ruby/gems/2.7.0/gems/shoryuken-5.0.4/lib/shoryuken/middleware/chain.rb:103:in `invoke'
/usr/lib/ruby/gems/2.7.0/gems/shoryuken-5.0.4/lib/shoryuken/processor.rb:20:in `block in process'
/usr/lib/ruby/gems/2.7.0/gems/shoryuken-5.0.4/lib/shoryuken/logging.rb:20:in `with_context'
/usr/lib/ruby/gems/2.7.0/gems/shoryuken-5.0.4/lib/shoryuken/processor.rb:19:in `process'
/usr/lib/ruby/gems/2.7.0/gems/shoryuken-5.0.4/lib/shoryuken/processor.rb:8:in `process'
/usr/lib/ruby/gems/2.7.0/gems/shoryuken-5.0.4/lib/shoryuken/manager.rb:73:in `block in assign'
/usr/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
/usr/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:41:in `block in synchronize'
/usr/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
/usr/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
/usr/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:19:in `execute'
/usr/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/promise.rb:563:in `block in realize'
/usr/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:353:in `run_task'
/usr/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:342:in `block (3 levels) in create_worker'
/usr/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:325:in `loop'
/usr/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:325:in `block (2 levels) in create_worker'
/usr/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:324:in `catch'
/usr/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:324:in `block in create_worker'

```

This likely happened when our AWS policy changed our access to SQS.  It'd be nice if this gem somehow caught this exception and reported it rollbar.

**Comment by h3poteto** [comment]
Thank you for using.
Hmm... I'm not sure. I will investigate it, but maybe it won't work.
